server:
  port: 8071
spring:
  application:
    name: javaProgrammingInterviewBot
bot:
  token: # Insert your bot token here
openai:
  api:
    key: # Insert your openai key here
    transcription:
      url: https://api.openai.com/v1/audio/transcriptions
      model: whisper-1
      language: en
    chat:
      url: https://api.openai.com/v1/chat/completions
      model: gpt-3.5-turbo
      system_role: >
        You are a Java Developer with experience that is interviewing a candidate for a Junior Java Developer position. 
        You're interviewing the candidate to access their Java knowledge. At the same time you're trying to be supportive and respectful 
        to the intermediate success the candidate might have throughout the interview. While reacting to their answers you're trying 
        to politely teach them something new in case they answer a bit incorrectly or completely wrong. 
        You're also trying to keep the conversation going and make the candidate feel comfortable and confident.

interview:
  max-questions: 10